# Generated by Django 5.1.6 on 2025-02-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('gin', 'Gin'), ('vodka', 'Vodka'), ('whiskey', 'Whiskey'), ('wine', 'Wine')], max_length=50, unique=True)),
                ('friendly_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('gin', 'Gin'), ('vodka', 'Vodka'), ('whiskey', 'Whiskey'), ('wine', 'Wine')], default='gin', max_length=50)),
                ('sku', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('alcohol_percentage', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('volume_ml', models.PositiveIntegerField(blank=True, help_text='Volume in milliliters (ml)', null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
            ],
        ),
    ]
